config/routes.rb
Videoapp::Application.routes.draw do

  match '/index', :to => 'videos#index'
  match '/show',   :to => 'videos#show'
  match '/new',    :to => 'videos#new'

  root :to => 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  # Paperclip
  # http://www.thoughtbot.com/projects/paperclip
  has_attached_file :source

  # Paperclip Validations
  validates_attachment_presence :source
  validates_attachment_content_type :source, :content_type => 'video/quicktime'
end
  # Acts as State Machine
  # http://elitists.textdriven.com/svn/plugins/acts_as_state_machine
  acts_as_state_machine :initial => :pending
  state :pending
  state :converting
  state :converted, :enter => :set_new_filename
  state :error
  
  event :convert do
    transitions :from => :pending, :to => :converting
  end
  
  event :converted do
    transitions :from => :converting, :to => :converted
  end
  
  event :failed do
    transitions :from => :converting, :to => :error
  end

  # This method is called from the controller and takes care of the converting
def convert
  self.convert!
  success = system(convert_command)
  if success && $?.exitstatus == 0
    self.converted!
  else
    self.failure!
  end
end

  protected
  
  def convert_command
  
  #construct new file extension
    flv =  "." + id.to_s + ".flv"

  #build the command to execute ffmpeg
    command = <<-end_command
     ffmpeg -i #{ RAILS_ROOT + '/public' + public_filename }  -ar 22050 -ab 32 -s 480x360 -vcodec flv -r 25 -qscale 8 -f flv -y #{ RAILS_ROOT + '/public' + public_filename + flv }
      
    end_command
    
    logger.debug "Converting video...command: " + command
    command
  end

  # This updates the stored filename with the new flash video file
  def set_new_filename
    update_attribute(:filename, "#{filename}.#{id}.flv")
    update_attribute(:content_type, "application/x-flash-video")
  end


  # This method is called from the controller and takes care of the converting
  def convert
    self.convert!

  #spawn a new thread to handle conversion
  spawn do

     success = system(convert_command)
     logger.debug 'Converting File: ' + success.to_s
     if success && $?.exitstatus == 0
       self.converted!
     else
       self.failure!
     end
  end #spawn
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  
  def index
    @videos = Video.find :all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(params[:video])
    if @video.save
      @video.convert
      flash[:notice] = 'Video has been uploaded'
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def show
    @video = Video.find(params[:id])
  end
  
  def delete
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

  <head>
    <title>Video Tutorial</title>
      <%= stylesheet_link_tag 'style' %>
    <%= javascript_include_tag 'flowplayer' %>   
  </head>

  <body>
    <h1>Video Tutorial</h1>
    
    <% flash.each do |key,value| %>

      <div id="flash" class="flash_<%= key %>" >
        <span class="message"><%= value %></span>
      </div>

    <% end -%>

    <%= yield :layout %>

  </body>

</html>

app/views/videos/index.html.erb
<h2>Videos</h2><br />

<%= link_to 'New Video', new_video_url %><br />
<% for video in @videos do %>
  <p><%= link_to video.title, video %></p>
<% end %>

app/views/videos/new.html.erb
<h2>New Video</h2><br />

<% form_for(@video, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>
  <table>
    <tr>
      <td><%= f.label :title %>: </td><td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td><%= f.label :description %>: </td><td><%= f.text_area :description %></td>
    </tr>
    <tr>
      <td><%= f.label :video %>: </td><td><%= f.file_field :uploaded_data %></td>
    </tr>    
    <tr><td><%= f.submit 'Submit' %> - <%= link_to 'Back', videos_path %></td></tr>
  </table>

<% end %>

app/views/videos/show.html.erb
<h1><%= @video.title %></h1>
<p><%= @video.description %></p>

  <a  
    href="<%= @video.public_filename %>"  
    style="display:block;width:400px;height:300px"  
    id="player"> 
  </a> 
   
  <!-- this will install flowplayer inside previous A- tag. -->
  <script>
   flowplayer("player", "/flowplayer/flowplayer-3.0.3.swf");
  </script>